### ISSUE TITLE
z always goes into .git directory

### ISSUE THREAD

**Issue by autoferrit** [fisherman/z#22] opened 2016-10-27 17:01 UTC
First, i pretty much never manually `cd` into a projects git directory. But, when i open a fresh shell prompt, and type 

```
z myproject
```

is always brings me to 

```
~/code/github.com/skift/myproject/.git
```

and it does this for other projects too that have a `.git` directory. whenever I do `z project` it brings me into `project/.git`

I don't see any configuration options that relate to this. I want `z` to completely ignore ever going into a `.git` folder, as well as it not try and remember those. 

I have also edited `~/.z` to remove any lines that reference `.git` but once i `cd` into a project again it is there in my .z file both the main project directory, and one with `.git` appended

**Comment by jethrokuan** [comment] 2016-10-28 01:35
Hi there,

I highly doubt that this behaviour is caused by `z`. `z` is not git-aware, and this doesn't happen to me while working with git projects.

I suspect that this behaviour is caused by other fish plugins you have installed. 

That said, I missed out the documentation for `Z_EXCLUDE`. I think

```
set -U Z_EXCLUDE ".git"
```

would be a hot-fix to your problem, but I suggest taking another look at the rest of your plugins and finding out what's causing this issue.

**Comment by autoferrit** [comment] 2016-10-30 07:53
Yea, ill try that for now. For reference, my installed plugins (via fisherman) are listed below

```
autoenvstack
await
bass
batman
bobthefish
brew
docker-completion
dpaste
emacs
fzf
getopts
git_util
grc
imgcat
last_job_id
pisces
pyenv
python
spin
tmux
z
```

**Comment by jethrokuan** [comment] 2017-01-24 03:05
Closing this for now, feel free to reopen if it happens again.

**Closed by jethrokuan** 2017-01-24 03:05 UTC
